name: strix-penetration-test

on:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Strix
        run: curl -sSL https://strix.ai/install | bash

      - name: Run Strix
        env:
          STRIX_LLM: ${{ secretsSTRIXLLM }}
          LLM_API_KEY: ${{ secretsLLMAPIKEY }}

        run: strix -n -t ./ --scan-mode quick
